Fix incompatibility in cake script when multiple versions of .Net Core are installed on Windows 10
When both .Net Core 3.1 & 2.1 are both installed, cake script aborts during BuildTools portion with the following message:

C:\Program Files\dotnet\sdk\2.1.512\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.1. [\MonoGame\Tools\MonoGame.Content.Builder\MonoGame.Content.Builder.csproj]
An error occurred when executing task 'BuildTools'.
Error: One or more errors occurred. (MSBuild: Process returned an error (exit code 1).)
        MSBuild: Process returned an error (exit code 1).